import Link from "next/link";
import { Shield, Layers, ArrowRight, Calendar, Lock, Cpu, Zap, ChevronRight } from "lucide-react";
import { MOCK_TEAMS } from "@/data/mock-teams";
import { MOCK_EVENTS } from "@/data/mock-events";

export default function Home() {
  return <div className="relative min-h-screen flex flex-col justify-between overflow-hidden bg-background">
    <div className="pointer-events-none absolute -left-24 top-24 h-72 w-72 rounded-full bg-[#a67c52]/10 blur-3xl" />
    <div className="pointer-events-none absolute -right-24 top-[42%] h-80 w-80 rounded-full bg-[#795548]/10 blur-3xl" />

    <header className="relative z-10 mx-auto flex w-full max-w-7xl items-center justify-between border-b border-[#d8c7b5] px-6 py-5">
      <div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#5d4037] text-[#fff8ef]"><Shield className="h-5 w-5" /></div><div><h1 className="text-base font-bold tracking-wide text-[#3e2723]">CSI Command Center</h1><p className="text-[10px] font-medium tracking-wide text-[#8d6e63]">Committee operations platform</p></div></div>
      <div className="flex items-center gap-3"><Link href="/login" className="hidden rounded-lg px-3.5 py-2 text-xs font-semibold text-[#6f625a] transition-colors hover:bg-[#e3d4c2] hover:text-[#3e2723] sm:inline-flex"><Lock className="mr-1.5 h-3.5 w-3.5" />Sign in</Link><Link href="/app/dashboard" className="inline-flex items-center gap-2 rounded-lg bg-[#5d4037] px-4 py-2.5 text-xs font-bold text-[#fff8ef] shadow-sm transition-colors hover:bg-[#3e2723]"><span>Open workspace</span><ArrowRight className="h-3.5 w-3.5" /></Link></div>
    </header>

    <main className="relative z-10 mx-auto w-full max-w-7xl px-6 py-16 sm:py-20">
      <div className="max-w-3xl space-y-6"><div className="inline-flex items-center gap-2 rounded-full border border-[#cdb8a5] bg-[#eadfd5] px-3 py-1 text-xs font-semibold text-[#6b5147]"><span className="h-2 w-2 rounded-full bg-[#a67c52]" />Built for CSI committee coordination</div><h2 className="text-4xl font-extrabold leading-[1.08] tracking-tight text-[#2e211d] sm:text-6xl">One committee.<br /><span className="text-[#795548]">Connected teams.</span><br />Smarter execution.</h2><p className="max-w-2xl text-base leading-relaxed text-[#6f625a] sm:text-lg">A centralized management platform for the College CSI Committee—connecting teams, project work, event workflows, rosters, and day-to-day decisions in one calm workspace.</p><div className="flex flex-wrap items-center gap-4 pt-2"><Link href="/app/dashboard" className="inline-flex items-center gap-2 rounded-xl bg-[#5d4037] px-6 py-3 text-sm font-bold text-[#fff8ef] shadow-sm transition-colors hover:bg-[#3e2723]">Explore workspace <ArrowRight className="h-4 w-4" /></Link><Link href="/app/teams" className="inline-flex items-center gap-2 rounded-xl border border-[#b89e88] bg-[#fffdf8] px-5 py-3 text-sm font-semibold text-[#5d4037] transition-colors hover:bg-[#e3d4c2]"><Layers className="h-4 w-4" />Inspect team portals</Link></div></div>

      <div className="mt-20 grid grid-cols-1 gap-5 md:grid-cols-3"><Feature icon={Zap} title="Cross-team coordination">Automated workflows connect Graphics, Technical, Publicity, and Event Management with less manual friction.</Feature><Feature icon={Lock} title="Role-aware access">Clear permissions for Faculty Sponsors, Core Committee, Advisory Board, Team Leads, Members, and Volunteers.</Feature><Feature icon={Cpu} title="Operational clarity">Project timelines, tasks, alerts, approvals, and activity stay visible in one unified workspace.</Feature></div>

      <section className="mt-24"><SectionHeading eyebrow="Organizational roster" title="9 specialized teams" href="/app/teams" label="View team directory" /><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{MOCK_TEAMS.map((team) => <div key={team.id} className="group rounded-xl border border-[#d8c7b5] bg-[#fffdf8] p-5 shadow-sm transition-all hover:-translate-y-0.5 hover:border-[#a67c52]"><div className="flex items-start justify-between"><span className="text-sm font-bold text-[#3e2723]">{team.name}</span><span className="rounded-full bg-[#e8ddd0] px-2 py-0.5 text-[10px] font-medium text-[#756b63]">{team.memberCount} members</span></div><p className="mt-1 text-xs font-medium text-[#8d6e63]">Lead: {team.leadName || team.teamLead?.fullName || 'Assigned'}</p><p className="mt-2 line-clamp-2 text-xs leading-relaxed text-[#6f625a]">{team.description}</p></div>)}</div></section>

      <section className="mt-24"><SectionHeading eyebrow="Upcoming schedule" title="Flagship events" href="/app/events" label="View events" /><div className="grid grid-cols-1 gap-5 md:grid-cols-3">{MOCK_EVENTS.map((event) => <div key={event.id} className="flex flex-col justify-between rounded-xl border border-[#d8c7b5] bg-[#fffdf8] p-5 shadow-sm transition-all hover:-translate-y-0.5 hover:border-[#a67c52]"><div><div className="mb-2 flex items-center gap-2 text-[10px] font-semibold text-[#795548]"><Calendar className="h-3.5 w-3.5" />{new Date(event.startDatetime).toLocaleDateString()}</div><h4 className="text-sm font-bold text-[#3e2723]">{event.name}</h4><p className="mt-1.5 line-clamp-2 text-xs leading-relaxed text-[#6f625a]">{event.description}</p></div><div className="mt-4 flex items-center justify-between border-t border-[#e8ddd0] pt-3 text-xs text-[#8d6e63]"><span>{event.venue}</span><span className="font-semibold text-[#795548]">{event.status}</span></div></div>)}</div></section>

      <section className="mt-24 flex flex-col items-center justify-between gap-6 rounded-2xl bg-[#3e2723] p-8 shadow-lg md:flex-row"><div className="space-y-1 text-center md:text-left"><h3 className="text-xl font-bold text-[#fff8ef]">Ready to explore the workspace?</h3><p className="text-xs text-[#e8ddd2]">Switch between demo personas and review the committee operating model.</p></div><Link href="/app/dashboard" className="inline-flex items-center gap-2 whitespace-nowrap rounded-xl bg-[#fff8ef] px-6 py-3 text-sm font-bold text-[#3e2723] transition-colors hover:bg-[#e3d4c2]">Open command center <ArrowRight className="h-4 w-4" /></Link></section>
    </main>
    <footer className="relative z-10 mx-auto flex w-full max-w-7xl flex-col items-center justify-between gap-3 border-t border-[#d8c7b5] px-6 py-8 text-xs text-[#8d6e63] sm:flex-row"><div>CSI Command Center © 2026</div><div>Cosmozic27/csi-command-center · main</div></footer>
  </div>;
}

function Feature({ icon: Icon, title, children }: { icon: typeof Zap; title: string; children: string }) { return <div className="rounded-2xl border border-[#d8c7b5] bg-[#fffdf8] p-6 shadow-sm"><div className="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-[#e8ddd0] text-[#795548]"><Icon className="h-5 w-5" /></div><h3 className="mb-2 text-base font-bold text-[#3e2723]">{title}</h3><p className="text-xs leading-relaxed text-[#6f625a]">{children}</p></div>; }
function SectionHeading({ eyebrow, title, href, label }: { eyebrow: string; title: string; href: string; label: string }) { return <div className="mb-8 flex items-end justify-between"><div><span className="text-xs font-semibold text-[#8d6e63]">{eyebrow}</span><h3 className="mt-1 text-2xl font-bold tracking-tight text-[#3e2723]">{title}</h3></div><Link href={href} className="flex items-center gap-1 text-xs font-semibold text-[#795548] hover:text-[#3e2723]">{label}<ChevronRight className="h-4 w-4" /></Link></div>; }
