'use client';

import Link from "next/link";
import { useEffect, useState } from "react";
import { Shield, ArrowRight, Lock, ChevronRight, CheckCircle2, Users, FolderKanban, HelpCircle, Mail, Plus, Minus } from "lucide-react";
import { MOCK_TEAMS } from "@/data/mock-teams";
import { MOCK_EVENTS } from "@/data/mock-events";
import { MOCK_PROJECTS } from "@/data/mock-projects";
import { MOCK_TASKS } from "@/data/mock-tasks";
import { Magnetic, Reveal, SpotlightCard } from "@/components/experience/ExperienceLayer";
import Topography from "@/components/Topography";

const sections = [
  ['overview', 'Overview'], ['teams', 'Teams'], ['workflow', 'Workflow'], ['events', 'Events'], ['capabilities', 'Capabilities'], ['faq', 'FAQ'], ['contact', 'Contact'],
];
const faqs = [
  ['What is CSI Command Center?', 'A shared workspace for coordinating committee teams, tasks, projects, files, events, approvals, and activity.'],
  ['Who can use the platform?', 'Faculty sponsors, core committee members, team leads, team members, advisory members, and general volunteers can use role-aware workspace views.'],
  ['What teams are supported?', 'The workspace supports the nine CSI operating teams represented in the committee roster.'],
  ['How are tasks assigned?', 'Tasks can be organized by team, owner, status, priority, project, and due date so responsibilities remain visible.'],
  ['How do teams collaborate?', 'Projects, events, files, comments, activity, and team portals keep cross-team handoffs visible without replacing existing team workflows.'],
];

export default function Home() {
  const [active, setActive] = useState('overview');
  const [progress, setProgress] = useState(0);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  useEffect(() => {
    const update = () => {
      const max = document.documentElement.scrollHeight - window.innerHeight;
      setProgress(max > 0 ? (window.scrollY / max) * 100 : 0);
      const current = sections.map(([id]) => document.getElementById(id)).filter(Boolean).reverse().find((node) => (node as HTMLElement).getBoundingClientRect().top <= 150);
      if (current) setActive(current.id);
    };
    update(); window.addEventListener('scroll', update, { passive: true });
    return () => window.removeEventListener('scroll', update);
  }, []);

  return <div className="relative min-h-screen overflow-hidden bg-background text-foreground">
    <div className="pointer-events-none absolute inset-x-0 top-0 z-0 h-[620px] opacity-25 sm:h-[700px]" aria-hidden="true"><Topography lowColor="#D8C0A8" midColor="#A67C52" highColor="#5D4037" speed={0.12} morphSpeed={0.035} bands={1.65} thickness={0.008} scale={1.15} glow={0.08} contrast={2.2} brightness={0.9} opacity={0.48} grain={false} mouseInteraction={false} className="h-full w-full" /></div>
    <div className="fixed left-0 top-0 z-50 h-0.5 bg-[#a67c52] transition-[width] duration-150" style={{ width: `${progress}%` }} />
    <div className="pointer-events-none absolute -left-24 top-24 h-72 w-72 rounded-full bg-[#a67c52]/10 blur-3xl" />
    <div className="pointer-events-none absolute -right-24 top-[42%] h-80 w-80 rounded-full bg-[#795548]/10 blur-3xl" />

    <header className="sticky top-0 z-40 border-b border-[#d8c7b5]/80 bg-[#f3ebdd]/90 backdrop-blur-xl"><div className="mx-auto flex w-full max-w-7xl items-center justify-between px-6 py-4"><Link href="#overview" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#5d4037] text-[#fff8ef]"><Shield className="h-5 w-5" /></span><span className="hidden text-sm font-bold tracking-wide text-[#3e2723] sm:block">CSI Command Center</span></Link><nav className="hidden items-center gap-5 lg:flex">{sections.map(([id, label]) => <a key={id} href={`#${id}`} className={`relative text-xs font-semibold transition-colors ${active === id ? 'text-[#3e2723]' : 'text-[#8d6e63] hover:text-[#5d4037]'}`}>{label}{active === id && <span className="absolute -bottom-4 left-0 right-0 h-0.5 rounded-full bg-[#5d4037]" />}</a>)}</nav><div className="flex items-center gap-2"><Magnetic><Link href="/login" className="hidden rounded-lg px-3 py-2 text-xs font-semibold text-[#6f625a] hover:bg-[#e3d4c2] sm:inline-flex"><Lock className="mr-1.5 h-3.5 w-3.5" />Sign in</Link></Magnetic><Magnetic><Link href="/app/dashboard" className="inline-flex items-center gap-2 rounded-lg bg-[#5d4037] px-3.5 py-2 text-xs font-bold text-[#fff8ef] shadow-sm hover:bg-[#3e2723]">Open workspace <ArrowRight className="h-3.5 w-3.5" /></Link></Magnetic></div></div></header>

    <main className="relative z-10 mx-auto w-full max-w-7xl px-6">
      <section id="overview" className="scroll-mt-24 py-20 sm:py-28"><Reveal><div className="max-w-4xl"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.18em] text-[#8d6e63]">01 · The committee workspace</p><h1 className="text-5xl font-extrabold leading-[1.02] tracking-tight text-[#2e211d] sm:text-7xl">CSI committee.<br /><span className="text-[#795548]">Connected teams.</span><br />Smarter execution.</h1><p className="mt-7 max-w-2xl text-base leading-relaxed text-[#6f625a] sm:text-lg">One calm operating layer for the College CSI Committee—bringing people, projects, tasks, files, events, approvals, and progress into focus.</p><div className="mt-8 flex flex-wrap gap-4"><Magnetic><Link href="/app/dashboard" className="inline-flex items-center gap-2 rounded-xl bg-[#5d4037] px-6 py-3 text-sm font-bold text-[#fff8ef] shadow-sm hover:bg-[#3e2723]">Explore workspace <ArrowRight className="h-4 w-4" /></Link></Magnetic><a href="#workflow" className="inline-flex items-center gap-2 rounded-xl border border-[#b89e88] bg-[#fffdf8] px-5 py-3 text-sm font-semibold text-[#5d4037] hover:bg-[#e3d4c2]">See how it connects <ChevronRight className="h-4 w-4" /></a></div></div></Reveal><div className="mt-16 grid gap-4 md:grid-cols-3"><MiniStat label="Teams represented" value={MOCK_TEAMS.length} icon={Users} /><MiniStat label="Projects in workspace" value={MOCK_PROJECTS.length} icon={FolderKanban} /><MiniStat label="Tracked tasks" value={MOCK_TASKS.length} icon={CheckCircle2} /></div></section>

      <section id="teams" className="scroll-mt-24 border-t border-[#d8c7b5] py-20"><SectionLabel number="02" label="Connected teams" title="Nine groups, one shared rhythm." copy="Make ownership clear while keeping cross-team handoffs visible. Every team keeps its operational context without becoming isolated." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{MOCK_TEAMS.map((team, index) => <Reveal key={team.id} delay={index * 35}><SpotlightCard tilt className="group rounded-2xl border border-[#d8c7b5] bg-[#fffdf8] p-5 shadow-sm"><Link href={`/app/teams?team=${team.slug}`} className="block"><div className="flex items-start justify-between"><span className="text-sm font-bold text-[#3e2723] transition-colors group-hover:text-[#795548]">{team.name}</span><span className="text-xs font-semibold text-[#a67c52]">0{index + 1}</span></div><p className="mt-2 text-xs leading-relaxed text-[#6f625a]">{team.description}</p><div className="mt-4 flex items-center justify-between border-t border-[#e8ddd0] pt-3 text-[10px] text-[#8d6e63]"><span>{team.memberCount} members</span><span className="inline-flex items-center gap-1 text-[#795548]">Open team <ArrowRight className="h-3 w-3 transition-transform group-hover:translate-x-1" /></span></div></Link></SpotlightCard></Reveal>)}</div></section>

      <section id="workflow" className="scroll-mt-24 border-t border-[#d8c7b5] py-20"><SectionLabel number="03" label="Workflow" title="From idea to documented outcome." copy="A simple operating rhythm helps each team understand what happens next and where its work connects." /><div className="grid gap-3 md:grid-cols-6">{['Plan', 'Assign', 'Build', 'Review', 'Approve', 'Document'].map((step, index) => <Reveal key={step} delay={index * 60}><div className="relative rounded-2xl border border-[#d8c7b5] bg-[#fffdf8] p-5 text-center shadow-sm transition-all hover:-translate-y-1 hover:border-[#a67c52]"><span className="text-xs font-bold text-[#a67c52]">0{index + 1}</span><h3 className="mt-3 text-sm font-bold text-[#3e2723]">{step}</h3>{index < 5 && <span className="absolute -right-3 top-1/2 hidden h-px w-6 bg-[#cdb8a5] md:block" />}</div></Reveal>)}</div><div className="mt-10 rounded-2xl bg-[#3e2723] p-7 text-[#fff8ef] shadow-lg"><div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#d6b18a]">A shared handoff language</p><h3 className="mt-2 text-2xl font-bold">Event → Plan → Build → Promote → Execute → Document</h3></div><Link href="/app/projects" className="inline-flex items-center gap-2 self-start rounded-lg bg-[#fff8ef] px-4 py-2 text-xs font-bold text-[#3e2723] hover:bg-[#e3d4c2]">View projects <ArrowRight className="h-3.5 w-3.5" /></Link></div></div></section>

      <section id="events" className="scroll-mt-24 border-t border-[#d8c7b5] py-20"><SectionLabel number="04" label="Events & milestones" title="Keep the next important moment visible." copy="Events become easier to coordinate when dates, owners, statuses, and next actions sit in the same visual rhythm." /><div className="relative ml-3 border-l border-[#cdb8a5] pl-7 md:ml-0 md:grid md:grid-cols-3 md:gap-6 md:border-l-0 md:pl-0">{MOCK_EVENTS.slice(0, 3).map((event, index) => <Reveal key={event.id} delay={index * 70}><div className="relative mb-8 rounded-2xl border border-[#d8c7b5] bg-[#fffdf8] p-5 shadow-sm last:mb-0 md:mb-0"><span className="absolute -left-[35px] top-7 h-3 w-3 rounded-full border-2 border-[#f3ebdd] bg-[#795548] md:static md:mb-5 md:block" /><p className="text-xs font-semibold text-[#795548]">{new Date(event.startDatetime).toLocaleDateString()}</p><h3 className="mt-2 text-base font-bold text-[#3e2723]">{event.name}</h3><p className="mt-1 text-xs leading-relaxed text-[#6f625a]">{event.description}</p><div className="mt-4 flex items-center justify-between border-t border-[#e8ddd0] pt-3 text-[10px] text-[#8d6e63]"><span>{event.venue}</span><span className="font-semibold text-[#795548]">{event.status}</span></div></div></Reveal>)}</div></section>

      <section id="capabilities" className="scroll-mt-24 border-t border-[#d8c7b5] py-20"><SectionLabel number="05" label="Capabilities" title="Everything the committee needs to keep moving." copy="Focused tools, connected through one shared operating model." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{['Team coordination', 'Task management', 'Event operations', 'Cross-team workflows', 'Files & approvals', 'Analytics', 'Member management', 'Automation'].map((item, index) => <Reveal key={item} delay={index * 30}><SpotlightCard className="rounded-2xl border border-[#d8c7b5] bg-[#fffdf8] p-5 shadow-sm"><span className="text-xs font-bold text-[#a67c52]">0{index + 1}</span><h3 className="mt-8 text-sm font-bold text-[#3e2723]">{item}</h3><p className="mt-2 text-xs leading-relaxed text-[#6f625a]">A clearer way to organize committee work and decisions.</p></SpotlightCard></Reveal>)}</div></section>

      <section className="border-t border-[#d8c7b5] py-20"><SectionLabel number="06" label="Impact at a glance" title="A calmer view of committee operations." copy="Live workspace counts are drawn from the existing project data, not invented marketing claims." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Impact value={MOCK_TEAMS.length} suffix="" label="Teams" detail="Operating groups represented" /><Impact value={MOCK_EVENTS.length} suffix="" label="Events" detail="Events currently in the workspace" /><Impact value={MOCK_PROJECTS.length} suffix="" label="Projects" detail="Projects available for coordination" /><Impact value={MOCK_TASKS.length} suffix="" label="Tasks" detail="Tasks tracked across teams" /></div></section>

      <section id="faq" className="scroll-mt-24 border-t border-[#d8c7b5] py-20"><SectionLabel number="07" label="FAQ" title="A few useful answers." copy="The essentials for understanding the operating model." /><div className="mx-auto max-w-3xl divide-y divide-[#d8c7b5] rounded-2xl border border-[#d8c7b5] bg-[#fffdf8] px-6">{faqs.map(([question, answer], index) => <div key={question} className="py-5"><button onClick={() => setOpenFaq(openFaq === index ? null : index)} className="flex w-full items-center justify-between gap-4 text-left text-sm font-semibold text-[#3e2723]"><span className="flex items-center gap-3"><HelpCircle className="h-4 w-4 text-[#a67c52]" />{question}</span>{openFaq === index ? <Minus className="h-4 w-4 text-[#795548]" /> : <Plus className="h-4 w-4 text-[#795548]" />}</button><div className={`grid transition-[grid-template-rows] duration-300 ${openFaq === index ? 'grid-rows-[1fr]' : 'grid-rows-[0fr]'}`}><p className="overflow-hidden pl-7 pt-3 text-xs leading-relaxed text-[#6f625a]">{answer}</p></div></div>)}</div></section>

      <section id="contact" className="scroll-mt-24 border-t border-[#d8c7b5] py-20"><SectionLabel number="08" label="Connect with CSI" title="Need a clearer next step?" copy="Open the workspace to explore the current committee operating model, or start with the public directory." /><div className="flex flex-wrap gap-4"><Magnetic><Link href="/app/dashboard" className="inline-flex items-center gap-2 rounded-xl bg-[#5d4037] px-6 py-3 text-sm font-bold text-[#fff8ef] hover:bg-[#3e2723]">Open command center <ArrowRight className="h-4 w-4" /></Link></Magnetic><Link href="/app/teams" className="inline-flex items-center gap-2 rounded-xl border border-[#b89e88] bg-[#fffdf8] px-5 py-3 text-sm font-semibold text-[#5d4037] hover:bg-[#e3d4c2]"><Mail className="h-4 w-4" />Browse team directory</Link></div></section>
    </main>

    <footer className="border-t border-[#d8c7b5] bg-[#e8ddd0] px-6 py-12"><div className="mx-auto grid max-w-7xl gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><div className="flex items-center gap-2 text-sm font-bold text-[#3e2723]"><Shield className="h-4 w-4" />CSI Command Center</div><p className="mt-3 max-w-xs text-xs leading-relaxed text-[#6f625a]">A shared operations platform for organized, transparent, and connected committee work.</p></div><FooterGroup title="Navigation" links={['Dashboard', 'Teams', 'Projects', 'Events']} hrefs={['/app/dashboard', '/app/teams', '/app/projects', '/app/events']} /><FooterGroup title="Resources" links={['Files', 'Calendar', 'Members', 'Analytics']} hrefs={['/app/files', '/app/calendar', '/app/members', '/app/analytics']} /><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#795548]">Connect</p><a href="#contact" className="mt-4 block text-xs text-[#6f625a] hover:text-[#3e2723]">Committee help & workspace access</a></div></div><div className="mx-auto mt-10 flex max-w-7xl flex-col justify-between gap-3 border-t border-[#d8c7b5] pt-5 text-[11px] text-[#8d6e63] sm:flex-row"><span>CSI Committee © 2026</span><span>Cosmozic27/csi-command-center · main</span></div></footer>
  </div>;
}

function SectionLabel({ number, label, title, copy }: { number: string; label: string; title: string; copy: string }) { return <div className="mb-10 max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#a67c52]">{number} · {label}</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-[#3e2723] sm:text-4xl">{title}</h2><p className="mt-3 text-sm leading-relaxed text-[#6f625a]">{copy}</p></div>; }
function MiniStat({ label, value, icon: Icon }: { label: string; value: number; icon: typeof Users }) { return <SpotlightCard className="rounded-2xl border border-[#d8c7b5] bg-[#fffdf8] p-5 shadow-sm"><Icon className="h-5 w-5 text-[#795548]" /><p className="mt-5 text-3xl font-bold text-[#3e2723]">{value}</p><p className="mt-1 text-xs text-[#6f625a]">{label}</p></SpotlightCard>; }
function Impact({ value, suffix, label, detail }: { value: number; suffix: string; label: string; detail: string }) { return <SpotlightCard className="rounded-2xl border border-[#d8c7b5] bg-[#fffdf8] p-6 shadow-sm"><p className="text-4xl font-extrabold text-[#5d4037]">{value}{suffix}</p><p className="mt-3 text-sm font-bold text-[#3e2723]">{label}</p><p className="mt-1 text-xs leading-relaxed text-[#6f625a]">{detail}</p></SpotlightCard>; }
function FooterGroup({ title, links, hrefs }: { title: string; links: string[]; hrefs: string[] }) { return <div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#795548]">{title}</p><div className="mt-4 space-y-2">{links.map((link, index) => <Link key={link} href={hrefs[index]} className="block text-xs text-[#6f625a] hover:text-[#3e2723]">{link}</Link>)}</div></div>; }
